[package]
name = "circuits"
type = "bin"
authors = ["Boris,Elliot,Luiz"]
compiler_version = "0.10.5"

[dependencies]
ecrecover = { tag = "v0.10.1", git = "https://github.com/colinnielsen/ecrecover-noir" }
